import { Facility } from './types';

export const sampleFacilities: Facility[] = [
  {
    id: 'sample-1',
    name: 'Tribhuvan University Teaching Hospital',
    type: 'Hospital',
    province: 'Bagmati',
    district: 'Kathmandu',
    city: 'Kathmandu',
    lat: 27.7336,
    lng: 85.3297,
    services: 'Emergency, surgery, internal medicine, pediatrics, OB/GYN, radiology',
    phone: '+977-1-4412303',
    website: 'https://iom.edu.np',
    facebook: 'https://facebook.com/TUTH.Official',
    instagram: null,
    twitter: null,
    youtube: null,
    linkedin: null,
    source: 'osm',
    osmId: 'node/123456',
    updatedAt: new Date(),
  },
  {
    id: 'sample-2',
    name: 'Patan Hospital',
    type: 'Hospital',
    province: 'Bagmati',
    district: 'Lalitpur',
    city: 'Lalitpur',
    lat: 27.6686,
    lng: 85.3188,
    services: 'Emergency, general surgery, orthopedics, dental, laboratory',
    phone: '+977-1-5522266',
    website: 'https://www.patanhospital.org.np',
    facebook: 'https://facebook.com/patanhospital',
    instagram: 'https://instagram.com/patanhospital',
    twitter: null,
    youtube: null,
    linkedin: null,
    source: 'osm',
    osmId: 'node/234567',
    updatedAt: new Date(),
  },
  {
    id: 'sample-3',
    name: 'Bir Hospital',
    type: 'Hospital',
    province: 'Bagmati',
    district: 'Kathmandu',
    city: 'Kathmandu',
    lat: 27.7044,
    lng: 85.3148,
    services: 'Emergency, cardiology, neurology, nephrology, burn unit',
    phone: '+977-1-4221119',
    website: null,
    facebook: null,
    instagram: null,
    twitter: null,
    youtube: null,
    linkedin: null,
    source: 'osm',
    osmId: 'node/345678',
    updatedAt: new Date(),
  },
  {
    id: 'sample-4',
    name: 'Nepal Mediciti Hospital',
    type: 'Hospital',
    province: 'Bagmati',
    district: 'Lalitpur',
    city: 'Lalitpur',
    lat: 27.6551,
    lng: 85.3268,
    services: 'Multi-specialty, cardiac center, cancer care, joint replacement',
    phone: '+977-1-4217766',
    website: 'https://www.nepalmediciti.com',
    facebook: 'https://facebook.com/NepalMediciti',
    instagram: 'https://instagram.com/nepalmediciti',
    twitter: 'https://twitter.com/nepalmediciti',
    youtube: 'https://youtube.com/@nepalmediciti',
    linkedin: 'https://linkedin.com/company/nepal-mediciti',
    source: 'osm',
    osmId: 'node/456789',
    updatedAt: new Date(),
  },
  {
    id: 'sample-5',
    name: 'Himal Health Clinic',
    type: 'Clinic',
    province: 'Bagmati',
    district: 'Kathmandu',
    city: 'Kathmandu',
    lat: 27.7172,
    lng: 85.3240,
    services: 'General practice, vaccinations, health checkups',
    phone: '+977-1-4444555',
    website: null,
    facebook: 'https://facebook.com/himalhealthclinic',
    instagram: null,
    twitter: null,
    youtube: null,
    linkedin: null,
    source: 'manual',
    osmId: null,
    updatedAt: new Date(),
  },
  {
    id: 'sample-6',
    name: 'Pokhara Community Health Post',
    type: 'Health Post',
    province: 'Gandaki',
    district: 'Kaski',
    city: 'Pokhara',
    lat: 28.2096,
    lng: 83.9856,
    services: 'Primary care, maternal health, immunization, basic laboratory',
    phone: null,
    website: null,
    facebook: null,
    instagram: null,
    twitter: null,
    youtube: null,
    linkedin: null,
    source: 'osm',
    osmId: 'node/567890',
    updatedAt: new Date(),
  },
  {
    id: 'sample-7',
    name: 'Western Regional Hospital',
    type: 'Hospital',
    province: 'Gandaki',
    district: 'Kaski',
    city: 'Pokhara',
    lat: 28.2140,
    lng: 83.9912,
    services: 'Emergency, general medicine, surgery, maternity, ICU',
    phone: '+977-61-520066',
    website: null,
    facebook: 'https://facebook.com/WRHPokhara',
    instagram: null,
    twitter: null,
    youtube: null,
    linkedin: null,
    source: 'osm',
    osmId: 'node/678901',
    updatedAt: new Date(),
  },
  {
    id: 'sample-8',
    name: 'Chitwan Medical Pharmacy',
    type: 'Pharmacy',
    province: 'Bagmati',
    district: 'Chitwan',
    city: 'Bharatpur',
    lat: 27.6688,
    lng: 84.4318,
    services: 'Prescription medicines, OTC drugs, medical supplies',
    phone: '+977-56-520111',
    website: null,
    facebook: null,
    instagram: null,
    twitter: null,
    youtube: null,
    linkedin: null,
    source: 'osm',
    osmId: 'node/789012',
    updatedAt: new Date(),
  },
  {
    id: 'sample-9',
    name: 'Lumbini Provincial Hospital',
    type: 'Hospital',
    province: 'Lumbini',
    district: 'Rupandehi',
    city: 'Butwal',
    lat: 27.7007,
    lng: 83.4486,
    services: 'Emergency, general surgery, orthopedics, OB/GYN, pediatrics',
    phone: '+977-71-540111',
    website: null,
    facebook: null,
    instagram: null,
    twitter: null,
    youtube: null,
    linkedin: null,
    source: 'osm',
    osmId: 'node/890123',
    updatedAt: new Date(),
  },
  {
    id: 'sample-10',
    name: 'Biratnagar Eye Hospital',
    type: 'Clinic',
    province: 'Koshi',
    district: 'Morang',
    city: 'Biratnagar',
    lat: 26.4525,
    lng: 87.2718,
    services: 'Ophthalmology, eye surgery, optical services, vision screening',
    phone: '+977-21-471155',
    website: 'https://www.biratnagareye.org.np',
    facebook: 'https://facebook.com/BEHBiratnagar',
    instagram: null,
    twitter: null,
    youtube: null,
    linkedin: null,
    source: 'osm',
    osmId: 'node/901234',
    updatedAt: new Date(),
  },
];
